// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEAbZZPtSvckRCGMMwg6FF_9T4HfofXVM',
    appId: '1:443002421303:web:e51ba9c1d02aa5fd18bfb2',
    messagingSenderId: '443002421303',
    projectId: 'lafmv1-54128419-44603',
    authDomain: 'lafmv1-54128419-44603.firebaseapp.com',
    storageBucket: 'lafmv1-54128419-44603.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXr0s7yqihRxpeDqM4m3YLsYI-hx_7l8A',
    appId: '1:443002421303:android:a87d320783cf652618bfb2',
    messagingSenderId: '443002421303',
    projectId: 'lafmv1-54128419-44603',
    storageBucket: 'lafmv1-54128419-44603.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwv6FPFqjI1ATLoaWVEJX9IMhHUEw5Yf0',
    appId: '1:443002421303:ios:1d6820cf62cc8b5218bfb2',
    messagingSenderId: '443002421303',
    projectId: 'lafmv1-54128419-44603',
    storageBucket: 'lafmv1-54128419-44603.firebasestorage.app',
    iosBundleId: 'com.example.lafmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwv6FPFqjI1ATLoaWVEJX9IMhHUEw5Yf0',
    appId: '1:443002421303:ios:1d6820cf62cc8b5218bfb2',
    messagingSenderId: '443002421303',
    projectId: 'lafmv1-54128419-44603',
    storageBucket: 'lafmv1-54128419-44603.firebasestorage.app',
    iosBundleId: 'com.example.lafmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEAbZZPtSvckRCGMMwg6FF_9T4HfofXVM',
    appId: '1:443002421303:web:2061adf5a3475bef18bfb2',
    messagingSenderId: '443002421303',
    projectId: 'lafmv1-54128419-44603',
    authDomain: 'lafmv1-54128419-44603.firebaseapp.com',
    storageBucket: 'lafmv1-54128419-44603.firebasestorage.app',
  );
}
